# Test Compound

First get some data with compounding events

In [1]:
import pandas
import xarray
import numpy

import sys
sys.path.append(sys.path[0]+'/../..')

%run "../../utils/compound.ipynb"

Load up some test data and answers done by hand

In [2]:
indexDf = pandas.read_csv('testDataCompound/index.csv', index_col='index')
indexDf.columns.name='year'

testIndecesDa=xarray.DataArray(indexDf)

testIndecesDa=testIndecesDa.astype(float)
testIndecesDa['year'] = testIndecesDa.year.astype(float)

testIndecesXr=testIndecesDa.to_dataset('index')

In [3]:
testIndecesXr

<xarray.Dataset>
Dimensions:  (year: 90)
Coordinates:
  * year     (year) float64 1.988e+03 1.989e+03 1.99e+03 ... 2.076e+03 2.077e+03
Data variables:
    dmi      (year) float64 -4.356 -4.057 -5.953 -5.389 ... 0.7489 2.032 4.536
    sam      (year) float64 0.5416 1.868 2.657 9.939 ... 8.116 8.77 4.334 4.166
    nino34   (year) float64 -3.786 -5.126 -2.956 0.9963 ... 9.599 3.277 8.71
    james    (year) float64 -3.963 5.738 -1.518 1.586 ... 7.255 3.402 0.755
    fred     (year) float64 -3.708 -4.647 -0.9299 3.734 ... 5.906 3.234 5.469
    andrew   (year) float64 -0.02342 -5.848 -5.905 -5.554 ... 4.451 4.388 3.283

In [4]:
testCritDf = pandas.read_csv('testDataCompound/criteria.csv', header=None, index_col=0)

testCritDf.index.name='index'
testCritDf.columns.name='experiment'

testCriteriaDa=xarray.DataArray(testCritDf)

testCriteriaXr=testCriteriaDa.to_dataset('index')

testCriteriaXr

<xarray.Dataset>
Dimensions:     (experiment: 1)
Coordinates:
  * experiment  (experiment) int64 1
Data variables:
    dmi         (experiment) int64 4
    sam         (experiment) int64 5
    nino34      (experiment) int64 4
    james       (experiment) int64 2
    fred        (experiment) int64 2
    andrew      (experiment) int64 2

# Test apply criteria

Do the calculation

In [5]:
resultsPosDa, resultsNegDa = applyCriteria(testIndecesXr, testCriteriaXr)

Load up some answers done by hand

In [6]:
answerPosDf = pandas.read_csv('testDataCompound/posCriteriaAnswer.csv', index_col='index')
answerNegDf = pandas.read_csv('testDataCompound/negCriteriaAnswer.csv', index_col='index')

Compare

In [7]:
resultsPosDa[['dmi','sam','nino34']].isel(experiment=0).to_array().values

array([[False, False, False, False,  True,  True,  True, False, False,
        False, False,  True, False,  True,  True,  True, False,  True,
         True,  True, False,  True,  True,  True,  True,  True,  True,
        False,  True, False,  True,  True, False,  True,  True, False,
         True, False,  True, False, False, False, False,  True,  True,
        False,  True,  True, False,  True,  True, False,  True,  True,
         True,  True, False, False, False,  True,  True,  True,  True,
         True, False,  True,  True,  True, False,  True,  True, False,
         True, False,  True,  True,  True, False,  True,  True, False,
        False,  True,  True,  True, False, False, False, False,  True],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
     

In [8]:
numpy.isclose(resultsPosDa[['dmi','sam','nino34']].isel(experiment=0).to_array().values, answerPosDf)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
     

In [9]:
numpy.isclose(resultsNegDa[['dmi','sam','nino34']].isel(experiment=0).to_array().values, answerNegDf)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
     

In [10]:
resultsPosDa.to_array('index').sum(dim='index')

<xarray.DataArray (year: 90, experiment: 1)>
array([[0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [2],
       [0],
       [2],
       [2],
       [1],
       [0],
       [2],
       [2],
       [2],
...
       [2],
       [1],
       [2],
       [1],
       [2],
       [1],
       [2],
       [0],
       [1],
       [2],
       [1],
       [1],
       [2],
       [1],
       [2],
       [0],
       [1],
       [1],
       [0],
       [2]])
Coordinates:
  * year        (year) float64 1.988e+03 1.989e+03 ... 2.076e+03 2.077e+03
  * experiment  (experiment) int64 1

In [11]:
posCount = resultsPosDa.to_array('index').sum(dim='index')

negCount = resultsNegDa.to_array('index').sum(dim='index')

In [12]:

if (posCount>1).sum(dim='year').values!=33:
    print((posCount>1).sum(dim='year').values)
    raise EnvironmentError('Error found in applying criteria')

if (negCount>1).sum(dim='year').values!=2:
    print((negCount>1).sum(dim='year').values)
    raise EnvironmentError('Error found in applying criteria')

In [13]:
junkCriteria={'sam':22, 'enso34':22, 'iod':-23}

try:
    applyCriteria(testIndecesDa, junkCriteria)
except:
    #Do Nothing
    print()
else:
    raise EnvironmentError("Bad inputs not rejected")
    


#This is kinda intestering. It lets you put the inputs in in the wrong order.

try:
    xxDa = applyCriteria(testCriteriaDa, testIndecesDa)
except:
    #Do Nothing
    print()
else:
    raise EnvironmentError("Bad inputs not rejected")

# Test compound

In [14]:
answerNegCompoundDf = pandas.read_csv('testDataCompound/negCompoundAnswer.csv', index_col='index')

In [15]:
resultsNegCompoundDa=compound(resultsNegDa)

In [16]:
resultsNegCompoundDa

<xarray.Dataset>
Dimensions:     (experiment: 1, year: 90)
Coordinates:
  * year        (year) float64 1.988e+03 1.989e+03 ... 2.076e+03 2.077e+03
  * experiment  (experiment) int64 1
Data variables:
    nino34      (year, experiment) bool False True False ... False False False
    dmi         (year, experiment) bool True True True ... False False False
    sam         (year, experiment) bool False False False ... True False False
    nEvents     (year, experiment) int32 1 2 1 2 1 1 1 0 0 ... 0 0 1 1 1 1 1 0 0
    all3        (year, experiment) bool False False False ... False False False
    nino34+dmi  (year, experiment) bool False True False ... False False False
    nino34+sam  (year, experiment) bool False False False ... False False False
    dmi+sam     (year, experiment) bool False False False ... False False False
Attributes:
    all3:     ['nino34', 'dmi', 'sam']
    indeces:  ['nino34', 'dmi', 'sam']
    pairs:    ['nino34+dmi', 'nino34+sam', 'dmi+sam']

In [17]:
numpy.isclose(
    resultsNegCompoundDa[answerNegCompoundDf.index].isel(experiment=0).to_array().values, 
              answerNegCompoundDf
)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
     

# Test overlapping bin sum

In [18]:
answerNegOverlapDf = pandas.read_csv('testDataCompound/overlappingBinsAnswer.csv', index_col='index')

In [19]:
answerNegOverlapDf

2003  2013  2023  2033  2043  2053  2063
index                                               
dmi            4     0     0     0     0     0     0
sam           10    12    12    10     9    11    14
nino34         3     0     0     0     0     0     0
nEvents       17    12    12    10     9    11    14
all3           0     0     0     0     0     0     0
nino34+dmi     1     0     0     0     0     0     0
nino34+sam     0     0     0     0     0     0     0
dmi+sam        1     0     0     0     0     0     0

In [20]:
resultOverlapBinsDa=overlappingBinSum(resultsNegCompoundDa)

In [21]:
resultOverlapBinsDa[answerNegOverlapDf.index].isel(experiment=0).values

<bound method Mapping.values of <xarray.Dataset>
Dimensions:     (year: 7)
Coordinates:
    experiment  int64 1
  * year        (year) int32 2003 2013 2023 2033 2043 2053 2063
Data variables:
    dmi         (year) float64 4.0 0.0 0.0 0.0 0.0 0.0 0.0
    sam         (year) float64 10.0 12.0 12.0 10.0 9.0 11.0 14.0
    nino34      (year) float64 3.0 0.0 0.0 0.0 0.0 0.0 0.0
    nEvents     (year) float64 17.0 12.0 12.0 10.0 9.0 11.0 14.0
    all3        (year) float64 0.0 0.0 0.0 0.0 0.0 0.0 0.0
    nino34+dmi  (year) float64 1.0 0.0 0.0 0.0 0.0 0.0 0.0
    nino34+sam  (year) float64 0.0 0.0 0.0 0.0 0.0 0.0 0.0
    dmi+sam     (year) float64 1.0 0.0 0.0 0.0 0.0 0.0 0.0
Attributes:
    all3:     ['nino34', 'dmi', 'sam']
    indeces:  ['nino34', 'dmi', 'sam']
    pairs:    ['nino34+dmi', 'nino34+sam', 'dmi+sam']
    Bins:     Overlapping 30 year bins, seperating by 10 year intervals
    Year:     Midpoint of bin>

In [22]:
# For some reason the answer has ended up transposed?

numpy.isclose(
    resultOverlapBinsDa[answerNegCompoundDf.index].isel(experiment=0).to_array().values, 
    answerNegOverlapDf
)

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

# Test of combinational logic

In [58]:
numpy.isclose(
    (resultsNegCompoundDa.nEvents==1)&(resultsNegCompoundDa.nino34) ,
    answerNegCompoundDf.loc['nino34']&answerNegCompoundDf.loc['nEvents']
)

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])