# Test Compound

First get some data with compounding events

In [127]:
import pandas
import xarray
import numpy

%run "../../utils/compound.ipynb"

Load up some test data and answers done by hand

In [128]:
indexDf = pandas.read_csv('testDataCompound/index.csv', index_col='index')
indexDf.columns.name='year'

testIndecesDa=xarray.DataArray(indexDf)

testIndecesDa=testIndecesDa.astype(float)
testIndecesDa['year'] = testIndecesDa.year.astype(float)

In [131]:
testCritDf = pandas.read_csv('testDataCompound/criteria.csv', header=None, index_col=0)

testCritDf.index.name='index'
testCritDf.columns.name='experiment'

testCriteriaDa=xarray.DataArray(testCritDf)

testCriteriaDa

<xarray.DataArray (index: 6, experiment: 1)>
array([[4],
       [5],
       [4],
       [2],
       [2],
       [2]])
Coordinates:
  * index       (index) object 'dmi' 'sam' 'nino34' 'james' 'fred' 'andrew'
  * experiment  (experiment) int64 1

# Test apply criteria

Do the calculation

In [132]:
resultsPosDa, resultsNegDa = applyCriteria(testIndecesDa, testCriteriaDa)

Load up some answers done by hand

In [133]:
answerPosDf = pandas.read_csv('testDataCompound/posCriteriaAnswer.csv', index_col='index')
answerNegDf = pandas.read_csv('testDataCompound/negCriteriaAnswer.csv', index_col='index')

Compare

In [134]:
numpy.isclose(resultsPosDa.isel(experiment=0).sel(index=['dmi','sam','nino34']).values, answerPosDf)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
     

In [135]:
numpy.isclose(resultsNegDa.isel(experiment=0).sel(index=['dmi','sam','nino34']).values, answerNegDf)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
     

In [136]:
posCount = resultsPosDa.sum(dim='index')

negCount = resultsNegDa.sum(dim='index')

In [137]:
#should be 0 and 2

if (posCount>1).sum(dim='year').values!=33:
    print((posCount>1).sum(dim='year').values)
    raise EnvironmentError('Error found in applying criteria')

if (negCount>1).sum(dim='year').values!=2:
    print((negCount>1).sum(dim='year').values)
    raise EnvironmentError('Error found in applying criteria')

In [138]:
junkCriteria={'sam':22, 'enso34':22, 'iod':-23}

try:
    applyCriteria(testIndecesDa, junkCriteria)
except:
    #Do Nothing
    print()
else:
    raise EnvironmentError("Bad inputs not rejected")
    


#This is kinda intestering. It lets you put the inputs in in the wrong order.

#try
xxDa = applyCriteria(testCriteriaDa, testIndecesDa)
#except:
#    #Do Nothing
#    print()
#else:
#    raise EnvironmentError("Bad inputs not rejected")

# Test compound

In [49]:
answerNegCompoundDf = pandas.read_csv('testDataCompound/negCompoundAnswer.csv', index_col='index')

In [50]:
resultsNegCompoundDa=compound(resultsNegDa)

In [51]:
numpy.isclose(
    resultsNegCompoundDa.isel(experiment=0).sel(index=answerNegCompoundDf.index).values, 
              answerNegCompoundDf
)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
     

# Test overlapping bin sum

In [62]:
answerNegOverlapDf = pandas.read_csv('testDataCompound/overlappingBinsAnswer.csv', index_col='index')

In [107]:
answerNegOverlapDf

2003  2013  2023  2033  2043  2053  2063
index                                               
dmi            4     0     0     0     0     0     0
sam           10    12    12    10     9    11    14
nino34         3     0     0     0     0     0     0
count         17    12    12    10     9    11    14
all3           0     0     0     0     0     0     0
nino34+dmi     1     0     0     0     0     0     0
nino34+sam     0     0     0     0     0     0     0
dmi+sam        1     0     0     0     0     0     0

In [57]:
resultOverlapBinsDa=overlappingBinSum(resultsNegCompoundDa)

In [104]:
resultOverlapBinsDa.isel(experiment=0).sel(index=answerNegOverlapDf.index).values

array([[ 4., 10.,  3., 17.,  0.,  1.,  0.,  1.],
       [ 0., 12.,  0., 12.,  0.,  0.,  0.,  0.],
       [ 0., 12.,  0., 12.,  0.,  0.,  0.,  0.],
       [ 0., 10.,  0., 10.,  0.,  0.,  0.,  0.],
       [ 0.,  9.,  0.,  9.,  0.,  0.,  0.,  0.],
       [ 0., 11.,  0., 11.,  0.,  0.,  0.,  0.],
       [ 0., 14.,  0., 14.,  0.,  0.,  0.,  0.]])

In [106]:
# For some reason the answer has ended up transposed?

numpy.isclose(
    resultOverlapBinsDa.isel(experiment=0).sel(index=answerNegCompoundDf.index).values, 
    answerNegOverlapDf.transpose()
)

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])